CC=g++
CFLAGS = -O2

initializing-sdl: initializing-sdl.cpp
	$(CC) $(CFLAGS) -lSDL initializing-sdl.cpp -o ~/build/linux_game_programming/initializing-sdl
direct-pixel-drawing: direct-pixel-drawing.cpp
	$(CC) $(CFLAGS) -lSDL direct-pixel-drawing.cpp -o ~/build/linux_game_programming/direct-pixel-drawing
blitting-surfaces: blitting-surfaces.cpp
	$(CC) $(CFLAGS) -lSDL blitting-surfaces.cpp -o ~/build/linux_game_programming/blitting-surfaces
colorkeys: colorkeys.cpp
	$(CC) $(CFLAGS) -lSDL colorkeys.cpp -o ~/build/linux_game_programming/colorkeys
alpha-blending: alpha-blending.cpp
	$(CC) $(CFLAGS) -lSDL -lSDL_image alpha-blending.cpp -o ~/build/linux_game_programming/alpha-blending
sdl-anim1: sdl-anim1.cpp
	$(CC) $(CFLAGS) -lSDL -lSDL_image sdl-anim1.cpp -o ~/build/linux_game_programming/sdl-anim1
sdl-anim2: sdl-anim2.cpp
	$(CC) $(CFLAGS) -lSDL -lSDL_image sdl-anim2.cpp -o ~/build/linux_game_programming/sdl-anim2
mouse-events: mouse-events.cpp
	$(CC) $(CFLAGS) -lSDL mouse-events.cpp -o ~/build/linux_game_programming/mouse-events
keyboard-events: keyboard-events.cpp
	$(CC) $(CFLAGS) -lSDL keyboard-events.cpp -o ~/build/linux_game_programming/keyboard-events
sdl-threading: sdl-threading.cpp
	$(CC) $(CFLAGS) -lSDL sdl-threading.cpp -o ~/build/linux_game_programming/sdl-threading
audio: audio.cpp
	$(CC) $(CFLAGS) -lSDL audio.cpp -o ~/build/linux_game_programming/audio
tcp-client: tcp-client.cpp
	$(CC) $(CFLAGS) -lSDL tcp-client.cpp -o ~/build/linux_game_programming/tcp-client
tcp-server: tcp-server.cpp
	$(CC) $(CFLAGS) -lSDL tcp-server.cpp -o ~/build/linux_game_programming/tcp-server
timtetris: timtetris.cpp
	$(CC) $(CFLAGS) -lSDL -lSDL_image -g timtetris.cpp -o ~/build/linux_game_programming/timtetris
clean:
	rm *.o *
