USE playmat;

DELETE FROM CardData;
DELETE FROM PlayerCards WHERE username = 'admin';

CALL CardDataSet('Abandoned Castle Stronghold Yellow', 'Abandoned Castle', 'Stronghold', 'Yellow', '2', '', '2', '', true, false, false, '', '', 0, 'AbandonedCastle.jpg');
CALL CardDataSet('Abandoned Idol Foe Yellow', 'Abandoned Idol', 'Foe', 'Yellow', '3', '3', '3', '4', false, true, false, 'An Earth Spirit Corrupted by Wood. Can be exorcised.', '...the encroaching ivy that over grows and then roots out the soul and divides it from itself.... ~ Octavio Paz', 0, 'AbandonedIdol.jpg');
CALL CardDataSet('Adobe Avalanche Attack Yellow', 'Adobe Avalanche', 'Attack', 'Yellow', '2', '2', '', '', false, true, false, '', 'Adobe structures are extremely durable and account for the oldest buildings on the planet.', 0, 'AdobeAvalanche.jpg');
CALL CardDataSet('Agate Armor Permanent Yellow', 'Agate Armor', 'Permanent', 'Yellow', '1', '', '4', '', false, true, false, 'Reduce attacks on target player by 1', '', 0, 'AgateArmor.jpg');
CALL CardDataSet('Agate Comb Upgrade Yellow', 'Agate Comb', 'Upgrade', 'Yellow', '', '', '', '', true, false, false, '', '', 0, 'AgateComb.jpg');
CALL CardDataSet('Amazon Jungle Stronghold Green', 'Amazon Jungle', 'Stronghold', 'Green', '3', '', '4', '', false, true, false, '', '', 0, 'AmazonJungle.jpg');
CALL CardDataSet('Amusement Park Plot Red', 'Amusement Park', 'Plot', 'Red', '', '', '', '', false, true, false, 'Bravery', '', 0, 'AmusementPark.jpg');
CALL CardDataSet('Ancestral Home Goal Yellow', 'Ancestral Home', 'Goal', 'Yellow', '2', '', '', '3', true, false, false, 'Patience +1', '', 0, 'AncestralHome.jpg');
CALL CardDataSet('Ancient Enemy Goal Red', 'Ancient Enemy', 'Goal', 'Red', '4', '', '', '', true, false, false, 'Bravery +1', '', 0, 'AncientEnemy.jpg');
CALL CardDataSet('Ancient Shrine Stronghold White', 'Ancient Shrine', 'Stronghold', 'White', '3', '', '3', '', false, true, false, '', '', 0, 'AncientShrine.jpg');
CALL CardDataSet('Ankle Bells Upgrade White', 'Ankle Bells', 'Upgrade', 'White', '', '', '', '', false, true, false, '', '', 0, 'AnkleBells.jpg');
CALL CardDataSet('Apple Amber Amulet Upgrade Green', 'Apple Amber Amulet', 'Upgrade', 'Green', '', '', '', '', false, true, false, '', 'The fossilized resin of ancient trees usually ranges in color from deep brown to honey to pale milky yellow, but if exposed to heat can turn to a shade of green.', 0, 'AppleAmberAmulet.jpg');
CALL CardDataSet('Art Contest Encounter Green', 'Art Contest', 'Encounter', 'Green', '3', '', '6', '', true, false, false, 'Creativity +1', '', 0, 'ArtContest.jpg');
CALL CardDataSet('Avoid Motive Blue', 'Avoid', 'Motive', 'Blue', '3', '', '', '2', false, true, false, 'Diplomacy +1', '', 0, 'Avoid.jpg');
CALL CardDataSet('Baby Brother Ally Green', 'Baby Brother', 'Ally', 'Green', '', '', '', '', false, false, false, 'Exploring', '', 0, 'BabyBrother.jpg');
CALL CardDataSet('Babysitting Encounter Yellow', 'Babysitting', 'Encounter', 'Yellow', '2', '', '5', '', false, true, false, 'Patience +1', '', 0, 'Babysitting.jpg');
CALL CardDataSet('Banshee Foe White', 'Banshee', 'Foe', 'White', '2', '2', '1', '4', false, true, false, 'Takes an ally out of action, in sorrow, until Banshee is defeated or departs.', 'The wailing of the Banshee was said to signal the death of a loved one.', 0, 'Banshee.jpg');
CALL CardDataSet('Beach Plot Blue', 'Beach', 'Plot', 'Blue', '', '', '', '', true, false, false, 'Swimming', '', 0, 'Beach.jpg');
CALL CardDataSet('Blazing Arrow Attack Red', 'Blazing Arrow', 'Attack', 'Red', '1', '1', '', '', true, false, false, '', '', 0, 'BlazingArrow.jpg');
CALL CardDataSet('Blue Heart Heart Blue', 'Blue Heart', 'Heart', 'Blue', '', '', '', '', false, true, false, '', 'The heart has its reasons whereof reason knows nothing. ~ Blaise Pascal', 0, 'BlueHeart.jpg');
CALL CardDataSet('Blue Ice Comet Attack Blue', 'Blue Ice Comet', 'Attack', 'Blue', '3', '3', '', '', true, false, false, '', '', 0, 'BlueIceComet.jpg');
CALL CardDataSet('Bookstore Plot Blue', 'Bookstore', 'Plot', 'Blue', '', '', '', '', true, false, false, 'Language, Automatic Clue', 'The love of learning, the sequestered nooks, And all the sweet serenity of books. ~ Henry Wadsworth Longfellow', 0, 'Bookstore.jpg');
CALL CardDataSet('Brilliant Rose Attack Red', 'Brilliant Rose', 'Attack', 'Red', '1', '1', '', '', true, false, false, '', '', 0, 'BrilliantRose.jpg');
CALL CardDataSet('Burning Rider Foe Red', 'Burning Rider', 'Foe', 'Red', '3', '3', '3', '4', false, true, false, 'Attempts to lead Allies away as its attack until defeated. Will attack any player who attacks it.', '', 0, 'BurningRider.jpg');
CALL CardDataSet('Businesswoman Ally White', 'Businesswoman', 'Ally', 'White', '', '', '', '', true, false, false, 'Money', '', 0, 'Businesswoman.jpg');
CALL CardDataSet('Cake Shop Plot Yellow', 'Cake Shop', 'Plot', 'Yellow', '', '', '', '', false, true, false, 'Cooking', '', 0, 'CakeShop.jpg');
CALL CardDataSet('Canary Chorus Permanent Yellow', 'Canary Chorus', 'Permanent', 'Yellow', '3', '', '', '', true, false, false, 'Target is immune to possession by water AND protected against sound-based attacks', '', 0, 'CanaryChorus.jpg');
CALL CardDataSet('Capture Motive White', 'Capture', 'Motive', 'White', '2', '', '', '2', false, true, false, '', '', 0, 'Capture.jpg');
CALL CardDataSet('Cardinal Plot Red', 'Cardinal', 'Plot', 'Red', '', '', '', '', true, false, false, 'Fashion', '', 0, 'Cardinal.jpg');
CALL CardDataSet('Carmine Conflagration Attack Red', 'Carmine Conflagration', 'Attack', 'Red', '1', '1', '', '', true, false, false, '', '', 0, 'CarmineConflagration.jpg');
CALL CardDataSet('Carnelian Crossbow Attack Red', 'Carnelian Crossbow', 'Attack', 'Red', '2', '2', '', '', true, false, false, '', '', 0, 'CarnelianCrossbow.jpg');
CALL CardDataSet('Carpenter Plot Green', 'Carpenter', 'Plot', 'Green', '', '', '', '', true, false, false, 'Creativity', '', 0, 'Carpenter.jpg');
CALL CardDataSet('Cave Plot Yellow', 'Cave', 'Plot', 'Yellow', '', '', '', '', true, false, false, 'Patience OR Exploring', '', 0, 'Cave.jpg');
CALL CardDataSet('Celestial Retribution Attack White', 'Celestial Retribution', 'Attack', 'White', '2', '2', '', '', true, false, false, '', '', 0, 'CelestialRetribution.jpg');
CALL CardDataSet('Center of the Earth Stronghold Yellow', 'Center of the Earth', 'Stronghold', 'Yellow', '5', '', '4', '', false, true, false, '', '', 0, 'CenteroftheEarth.jpg');
CALL CardDataSet('Cerulean Spray Attack Blue', 'Cerulean Spray', 'Attack', 'Blue', '1', '1', '', '', true, false, false, '', '', 0, 'CeruleanSpray.jpg');
CALL CardDataSet('Chartreuse Chinook Instant Green', 'Chartreuse Chinook', 'Instant', 'Green', '1', '', '', '', false, true, false, 'A gentle spring breeze causes the target to regain 3 health', 'The Chinook is the first wind of spring. ~ the snow eater', 0, 'ChartreuseChinook.jpg');
CALL CardDataSet('Chef Plot Yellow', 'Chef', 'Plot', 'Yellow', '', '', '', '', false, false, false, 'Cooking', '', 0, 'Chef.jpg');
CALL CardDataSet('Cinnibar Pendant Upgrade Red', 'Cinnibar Pendant', 'Upgrade', 'Red', '', '', '', '', true, false, false, '', '', 0, 'CinnibarPendant.jpg');
CALL CardDataSet('Clack Foe White', 'Clack', 'Foe', 'White', '1', '1', '1', '2', true, false, false, 'Convertible, can simultaneously attack with Click', '', 0, 'Clack.jpg');
CALL CardDataSet('Classmate Ally Yellow', 'Classmate', 'Ally', 'Yellow', '', '', '', '', true, false, false, 'Friendship', '', 0, 'Classmate.jpg');
CALL CardDataSet('Click Foe White', 'Click', 'Foe', 'White', '1', '1', '1', '2', false, false, false, 'Convertible, can simultaneously attack with Clack', '', 0, 'Click.jpg');
CALL CardDataSet('Clown Plot Red', 'Clown', 'Plot', 'Red', '', '', '', '', false, true, false, 'Humor', 'I always thought that the high prince was the lion or the magician, but the clown is the most important.  ~ Roberto Benigni', 0, 'Clown.jpg');
CALL CardDataSet('Cobalt Centipede Foe Blue', 'Cobalt Centipede', 'Foe', 'Blue', '2', '3', '2', '3', true, false, false, '', '', 0, 'CobaltCentipede.jpg');
CALL CardDataSet('Conquer Motive White', 'Conquer', 'Motive', 'White', '3', '', '', '1', true, false, false, '', '', 0, 'Conquer.jpg');
CALL CardDataSet('Cooking Contest Encounter Yellow', 'Cooking Contest', 'Encounter', 'Yellow', '1', '', '4', '', false, true, false, 'Cooking +1', '', 0, 'CookingContest.jpg');
CALL CardDataSet('Cousin Ally Yellow', 'Cousin', 'Ally', 'Yellow', '', '', '', '', false, false, false, 'Crafts', '', 0, 'Cousin.jpg');
CALL CardDataSet('Crab Plot Blue', 'Crab', 'Plot', 'Blue', '', '', '', '', false, false, false, 'Patience', '', 0, 'Crab.jpg');
CALL CardDataSet('Cram School Plot Blue', 'Cram School', 'Plot', 'Blue', '', '', '', '', false, true, false, 'History', '', 0, 'CramSchool.jpg');
CALL CardDataSet('Crystal Caves Permanent Yellow', 'Crystal Caves', 'Permanent', 'Yellow', '1', '', '', '', false, true, false, 'Add +2 to maximum hand count', '', 0, 'CrystalCaves.jpg');
CALL CardDataSet('Crystal Unicorn Plot Yellow', 'Crystal Unicorn', 'Plot', 'Yellow', '', '', '', '', false, true, false, 'Patience', '', 0, 'CrystalUnicorn.jpg');
CALL CardDataSet('Damaged Dress Encounter Red', 'Damaged Dress', 'Encounter', 'Red', '1', '', '4', '', false, true, false, 'Fashion +1', '', 0, 'DamagedDress.jpg');
CALL CardDataSet('Dark Cloud Foe Blue', 'Dark Cloud', 'Foe', 'Blue', '3', '2', '3', '4', false, true, false, 'Possesses plot places, making them spooky and unusable unless Player has Bravery (or Foe is defeated or leaves).', '', 0, 'DarkCloud.jpg');
CALL CardDataSet('Deer Plot Green', 'Deer', 'Plot', 'Green', '', '', '', '', false, true, false, 'Exploring, Speed', '', 0, 'Deer.jpg');
CALL CardDataSet('Destroy Motive Red', 'Destroy', 'Motive', 'Red', '5', '', '', '4', false, true, false, '', '', 0, 'Destroy.jpg');
CALL CardDataSet('Detective Ally White', 'Detective', 'Ally', 'White', '', '', '', '', true, false, false, 'Organization and Secrets', '', 0, 'Detective.jpg');
CALL CardDataSet('Doctor Plot Blue', 'Doctor', 'Plot', 'Blue', '', '', '', '', false, true, false, 'HealthCan use action to restore one Health or return one Ally to Healthy status', '', 0, 'Doctor.jpg');
CALL CardDataSet('Electrum Net Permanent White', 'Electrum Net', 'Permanent', 'White', '', '', '', '', false, false, false, 'Protect against Wood possession', '', 0, 'ElectrumNet.jpg');
CALL CardDataSet('Emerald Nebula Attack Green', 'Emerald Nebula', 'Attack', 'Green', '2', '2', '', '', true, false, false, '', '', 0, 'EmeraldNebula.jpg');
CALL CardDataSet('Escape Motive Green', 'Escape', 'Motive', 'Green', '3', '', '', '2', true, false, false, 'Speed +1', '', 0, 'Escape.jpg');
CALL CardDataSet('Evergreen Enchantment Instant Green', 'Evergreen Enchantment', 'Instant', 'Green', '2', '', '', '', true, false, false, 'Exorcise Earth Foe', '', 0, 'EvergreenEnchantment.jpg');
CALL CardDataSet('Exam Encounter Blue', 'Exam', 'Encounter', 'Blue', '2', '', '5', '', false, true, false, 'History +1 OR Science +1', '', 0, 'Exam.jpg');
CALL CardDataSet('Face a Bully Encounter Red', 'Face a Bully', 'Encounter', 'Red', '2', '', '5', '', false, true, false, 'Bravery +1', '', 0, 'FaceaBully.jpg');
CALL CardDataSet('Falling Fieldstone Wall Permanent Yellow', 'Falling Fieldstone Wall', 'Permanent', 'Yellow', '2', '', '1', '', true, false, false, 'Protects one target, -1 to attacks', '', 0, 'FallingFieldstoneWall.jpg');
CALL CardDataSet('Family Member Goal Yellow', 'Family Member', 'Goal', 'Yellow', '5', '', '', '4', false, true, false, '', '', 0, 'FamilyMember.jpg');
CALL CardDataSet('Fashion Show Encounter Red', 'Fashion Show', 'Encounter', 'Red', '2', '', '5', '', true, false, false, 'Fashion +1', '', 0, 'FashionShow.jpg');
CALL CardDataSet('Father Ally White', 'Father', 'Ally', 'White', '', '', '', '', true, false, false, 'Confidence', '', 0, 'Father.jpg');
CALL CardDataSet('Feisty Fiesta Attack Red', 'Feisty Fiesta', 'Attack', 'Red', '1', '1', '', '', false, false, false, 'Target is immune to possession by Metal', '', 0, 'FeistyFiesta.jpg');
CALL CardDataSet('Fencing Match Encounter White', 'Fencing Match', 'Encounter', 'White', '2', '', '5', '', false, true, false, 'Sports +1', '', 0, 'FencingMatch.jpg');
CALL CardDataSet('Find Motive Blue', 'Find', 'Motive', 'Blue', '2', '', '', '2', true, false, false, 'Secrets +1', '', 0, 'Find.jpg');
CALL CardDataSet('Fire Toad Foe Red', 'Fire Toad', 'Foe', 'Red', '2', '2', '2', '3', false, true, false, '', '', 0, 'FireToad.jpg');
CALL CardDataSet('Fire Triangle Earrings Upgrade Red', 'Fire Triangle Earrings', 'Upgrade', 'Red', '', '', '', '', true, false, false, '', '', 0, 'FireTriangleEarrings.jpg');
CALL CardDataSet('Fisherman Plot Blue', 'Fisherman', 'Plot', 'Blue', '', '', '', '', true, false, false, 'Exploring', '', 0, 'Fisherman.jpg');
CALL CardDataSet('Florist Plot White', 'Florist', 'Plot', 'White', '', '', '', '', true, false, false, 'Organization', '', 0, 'Florist.jpg');
CALL CardDataSet('Flower Power Beads Upgrade Green', 'Flower Power Beads', 'Upgrade', 'Green', '', '', '', '', true, false, false, '', '', 0, 'FlowerPowerBeads.jpg');
CALL CardDataSet('Flower Show Encounter Green', 'Flower Show', 'Encounter', 'Green', '1', '', '5', '', true, false, false, 'Gardening OR Creativity +1', '', 0, 'FlowerShow.jpg');
CALL CardDataSet('Foot Race Encounter Green', 'Foot Race', 'Encounter', 'Green', '1', '', '4', '', false, true, false, 'Speed +1', '', 0, 'FootRace.jpg');
CALL CardDataSet('Forest Flutesong Instant Green', 'Forest Flutesong', 'Instant', 'Green', '2', '', '', '', true, false, false, 'Calms the soul. No player, foe, or possessed card may attack during the current player\'s turn (at time of card use).', 'Musick has Charms to sooth a savage Breast,To soften Rocks, or bend a knotted Oak. ~ William Congreve', 0, 'ForestFlutesong.jpg');
CALL CardDataSet('Fountain Plot Blue', 'Fountain', 'Plot', 'Blue', '', '', '', '', true, false, false, 'History', '', 0, 'Fountain.jpg');
CALL CardDataSet('Foxglove Foe Green', 'Foxglove', 'Foe', 'Green', '3', '2', '2', '3', false, true, false, 'Normal damage, +target must make a Bravery Encounter roll at 5+ or be afraid and unable to attack.', 'Foxglove is the source of the heart drug, digitalis.', 0, 'Foxglove.jpg');
CALL CardDataSet('Fragrant Chrysanthemum Attack White', 'Fragrant Chrysanthemum', 'Attack', 'White', '2', '2', '', '', false, true, false, '', '', 0, 'FragrantChrysanthemum.jpg');
CALL CardDataSet('Free Motive Green', 'Free', 'Motive', 'Green', '3', '', '', '3', false, true, false, '', '', 0, 'Free.jpg');
CALL CardDataSet('Gaia\'s Gift Permanent Green', 'Gaia\'s Gift', 'Permanent', 'Green', '', '', '', '', false, false, false, 'Give any card to another player anytime. The card returns to your discard pile when completed.', '', 0, 'Gaia\'sGift.jpg');
CALL CardDataSet('Gardener Ally Green', 'Gardener', 'Ally', 'Green', '', '', '', '', false, false, false, 'Gardening', '', 0, 'Gardener.jpg');
CALL CardDataSet('Geode Jewel Upgrade Yellow', 'Geode Jewel', 'Upgrade', 'Yellow', '', '', '', '', true, false, false, '', '', 0, 'GeodeJewel.jpg');
CALL CardDataSet('Giant Oyster Foe Blue', 'Giant Oyster', 'Foe', 'Blue', '1', '1', '1', '2', true, false, false, 'Will not attack a player with Cooking. Attacks player with Fashion first.', 'Out for revenge for all those pearls!', 0, 'GiantOyster.jpg');
CALL CardDataSet('Glittering Ice Chimes Attack Blue', 'Glittering Ice Chimes', 'Attack', 'Blue', '1', '', '', '', false, false, false, '', '', 0, 'GlitteringIceChimes.jpg');
CALL CardDataSet('Green Heart Heart Green', 'Green Heart', 'Heart', 'Green', '1', '', '', '', false, true, false, '', '', 0, 'GreenHeart.jpg');
CALL CardDataSet('Greenhouse Plot Green', 'Greenhouse', 'Plot', 'Green', '', '', '', '', true, false, false, 'Gardening', '', 0, 'Greenhouse.jpg');
CALL CardDataSet('Hand Flower Upgrade White', 'Hand Flower', 'Upgrade', 'White', '', '', '', '', false, true, false, '', '', 0, 'HandFlower.jpg');
CALL CardDataSet('Harvest Moon Halo Attack Yellow', 'Harvest Moon Halo', 'Attack', 'Yellow', '3', '3', '', '', true, false, false, '', '', 0, 'HarvestMoonHalo.jpg');
CALL CardDataSet('Hateful Sparks Foe Red', 'Hateful Sparks', 'Foe', 'Red', '1', '0', '1', '2', true, false, false, 'Hate - takes a Friend out of action', '', 0, 'HatefulSparks.jpg');
CALL CardDataSet('Haunted Forest Stronghold Green', 'Haunted Forest', 'Stronghold', 'Green', '3', '', '3', '', true, false, false, '', '', 0, 'HauntedForest.jpg');
CALL CardDataSet('Heart of a Volcano Stronghold Red', 'Heart of a Volcano', 'Stronghold', 'Red', '4', '', '4', '', true, false, false, '', '', 0, 'HeartofaVolcano.jpg');
CALL CardDataSet('Heaven\'s Lament Attack White', 'Heaven\'s Lament', 'Attack', 'White', '1', '1', '', '', true, false, false, '', '', 0, 'Heaven\'sLament.jpg');
CALL CardDataSet('Hemlock Foe Green', 'Hemlock', 'Foe', 'Green', '2', '0', '2', '4', true, false, false, 'Does no damage, but targets (players, allies, or people-plots) may not function until this foe is defeated or leaves.', 'Socrates was forced to drink a hemlock potion after being convicted by the ancient Greek court and sentanced to death.', 0, 'Hemlock.jpg');
CALL CardDataSet('Homeworld Goal Green', 'Homeworld', 'Goal', 'Green', '3', '', '', '3', false, true, false, 'Exploring +1', '', 0, 'Homeworld.jpg');
CALL CardDataSet('HotBot Foe White', 'HotBot', 'Foe', 'White', '3', '3', '3', '4', false, true, false, 'A Metal Spirit Corrupted by Fire - May be exorcised', '', 0, 'HotBot.jpg');
CALL CardDataSet('Identify Artifact Encounter Blue', 'Identify Artifact', 'Encounter', 'Blue', '3', '', '6', '', true, false, false, 'History +1 OR Language +1', '', 0, 'IdentifyArtifact.jpg');
CALL CardDataSet('Incredible Sale! Plot White', 'Incredible Sale!', 'Plot', 'White', '', '', '', '', false, true, false, 'Money', '', 0, 'IncredibleSale!.jpg');
CALL CardDataSet('Indigo Infinity Attack Blue', 'Indigo Infinity', 'Attack', 'Blue', '2', '3', '', '', true, false, false, '', '', 0, 'IndigoInfinity.jpg');
CALL CardDataSet('Injured Friend Encounter Yellow', 'Injured Friend', 'Encounter', 'Yellow', '2', '', '5', '', true, false, false, 'Health +1', '', 0, 'InjuredFriend.jpg');
CALL CardDataSet('Ivy Metallica Foe Green', 'Ivy Metallica', 'Foe', 'Green', '1', '1', '1', '2', false, true, false, 'A Wood Spirit Corrupted by Metal. Can be exorcised.', '', 0, 'IvyMetallica.jpg');
CALL CardDataSet('Jade Peony Barrettes Upgrade Green', 'Jade Peony Barrettes', 'Upgrade', 'Green', '', '', '', '', true, false, false, 'These barrettes sit at the side of the head, near the eyes', '', 0, 'JadePeonyBarrettes.jpg');
CALL CardDataSet('Jasmine Javelin Attack Green', 'Jasmine Javelin', 'Attack', 'Green', '1', '1', '', '', false, true, false, '', '', 0, 'JasmineJavelin.jpg');
CALL CardDataSet('Jasper Statuette Foe Yellow', 'Jasper Statuette', 'Foe', 'Yellow', '1', '1', '1', '2', true, false, false, 'Statuette which causes owner to worry. Target attacks and defends at -1 until this Foe is defeated or leaves.', '', 0, 'JasperStatuette.jpg');
CALL CardDataSet('Jeweled Tortoise Ally Blue', 'Jeweled Tortoise', 'Ally', 'Blue', '', '', '', '', false, false, false, 'Secrets', '', 0, 'JeweledTortoise.jpg');
CALL CardDataSet('Jewelry Store Plot White', 'Jewelry Store', 'Plot', 'White', '', '', '', '', false, false, false, 'Money', '', 0, 'JewelryStore.jpg');
CALL CardDataSet('Jungle Storm Attack Green', 'Jungle Storm', 'Attack', 'Green', '2', '2', '', '', true, false, false, '', '', 0, 'JungleStorm.jpg');
CALL CardDataSet('Keep a Secret Encounter Blue', 'Keep a Secret', 'Encounter', 'Blue', '1', '', '5', '', false, true, false, 'Secrets +1', '', 0, 'KeepaSecret.jpg');
CALL CardDataSet('Ki-Rin Goal Green', 'Ki-Rin', 'Goal', 'Green', '3', '', '', '2', true, false, false, 'History +1', 'A mythical creature of Japanese legend', 0, 'Ki-Rin.jpg');
CALL CardDataSet('Koi Plot Blue', 'Koi', 'Plot', 'Blue', '', '', '', '', false, true, false, 'Swimming', '', 0, 'Koi.jpg');
CALL CardDataSet('Lake Pollution Encounter Blue', 'Lake Pollution', 'Encounter', 'Blue', '2', '', '5', '', false, true, false, 'Science +1', '', 0, 'LakePollution.jpg');
CALL CardDataSet('Lapis Lazuli Locket Upgrade Blue', 'Lapis Lazuli Locket', 'Upgrade', 'Blue', '', '', '', '', false, true, false, '', '', 0, 'LapisLazuliLocket.jpg');
CALL CardDataSet('Leafy Lenses Upgrade Green', 'Leafy Lenses', 'Upgrade', 'Green', '', '', '', '', false, true, false, '', '', 0, 'LeafyLenses.jpg');
CALL CardDataSet('Librarian Plot Blue', 'Librarian', 'Plot', 'Blue', '', '', '', '', false, true, false, 'Language', '', 0, 'Librarian.jpg');
CALL CardDataSet('Lifeguard Plot Blue', 'Lifeguard', 'Plot', 'Blue', '', '', '', '', true, false, false, 'Swimming', '', 0, 'Lifeguard.jpg');
CALL CardDataSet('Lime Lariat Attack Green', 'Lime Lariat', 'Attack', 'Green', '1', '1', '', '', true, false, false, '', '', 0, 'LimeLariat.jpg');
CALL CardDataSet('Little Sister Ally Red', 'Little Sister', 'Ally', 'Red', '', '', '', '', false, false, false, 'Can give 1 Heart per this Player\'s Episode.', '', 0, 'LittleSister.jpg');
CALL CardDataSet('Lost Island Stronghold Blue', 'Lost Island', 'Stronghold', 'Blue', '3', '', '2', '', true, false, false, '', '', 0, 'LostIsland.jpg');
CALL CardDataSet('Lost Pet Encounter White', 'Lost Pet', 'Encounter', 'White', '1', '', '5', '', false, true, false, 'Intuition +1', '', 0, 'LostPet.jpg');
CALL CardDataSet('Magma Burst Attack Red', 'Magma Burst', 'Attack', 'Red', '2', '2', '', '', false, true, false, '', 'The molten layer below the Earth\'s crust can erupt where the crust is thin, causing volcanoes and geysers.', 0, 'MagmaBurst.jpg');
CALL CardDataSet('Magnetic Meteor Attack White', 'Magnetic Meteor', 'Attack', 'White', '3', '3', '', '', true, false, false, '', '', 0, 'MagneticMeteor.jpg');
CALL CardDataSet('Mahalat Foe Red', 'Mahalat', 'Foe', 'Red', '4', '4', '4', '8', true, false, false, 'Attacked players may not play Hearts until Mahalat is defeated or leaves.', '', 0, 'Mahalat.jpg');
CALL CardDataSet('Make a Gift Encounter Yellow', 'Make a Gift', 'Encounter', 'Yellow', '1', '', '4', '', false, true, false, 'Crafts +1', '', 0, 'MakeaGift.jpg');
CALL CardDataSet('Martial Artist Ally White', 'Martial Artist', 'Ally', 'White', '', '', '', '', false, true, false, 'Sports', '', 0, 'MartialArtist.jpg');
CALL CardDataSet('Money Worries Encounter White', 'Money Worries', 'Encounter', 'White', '1', '', '4', '', true, false, false, 'A friend has money problems and needs help  raising some money quickly. Money +1', '', 0, 'MoneyWorries.jpg');
CALL CardDataSet('Mother Ally White', 'Mother', 'Ally', 'White', '', '', '', '', true, false, false, 'Organization', '', 0, 'Mother.jpg');
CALL CardDataSet('Movie star Plot Red', 'Movie star', 'Plot', 'Red', '', '', '', '', true, false, false, 'Acting', 'It\'s far better to be looked over than overlooked. ~ Mae West', 0, 'Moviestar.jpg');
CALL CardDataSet('Mystical Amulet Goal Blue', 'Mystical Amulet', 'Goal', 'Blue', '2', '', '', '2', false, true, false, 'History +1', '', 0, 'MysticalAmulet.jpg');
CALL CardDataSet('Naamah Foe Blue', 'Naamah', 'Foe', 'Blue', '4', '3', '4', '8', true, false, false, 'Possess plot cards as Level 2 Foes', '', 0, 'Naamah.jpg');
CALL CardDataSet('Nature Hike Encounter Green', 'Nature Hike', 'Encounter', 'Green', '3', '', '6', '', false, true, false, 'Don\'t get lost! Exploring +1', '', 0, 'NatureHike.jpg');
CALL CardDataSet('Ochre Aftershock Attack Yellow', 'Ochre Aftershock', 'Attack', 'Yellow', '2', '2', '', '', true, false, false, '', '', 0, 'OchreAftershock.jpg');
CALL CardDataSet('Opal Ear Drops Upgrade Blue', 'Opal Ear Drops', 'Upgrade', 'Blue', '', '', '', '', true, false, false, '', '', 0, 'OpalEarDrops.jpg');
CALL CardDataSet('Orbiting Space Station Stronghold White', 'Orbiting Space Station', 'Stronghold', 'White', '4', '', '5', '', true, false, false, '', '', 0, 'OrbitingSpaceStation.jpg');
CALL CardDataSet('Organize School Festival Encounter White', 'Organize School Festival', 'Encounter', 'White', '2', '', '5', '', false, true, false, 'Organization +1', '', 0, 'OrganizeSchoolFestival.jpg');
CALL CardDataSet('Palace of the Sun Stronghold Red', 'Palace of the Sun', 'Stronghold', 'Red', '4', '', '5', '', false, true, false, '', '', 0, 'PalaceoftheSun.jpg');
CALL CardDataSet('Pearl Brooch Upgrade Blue', 'Pearl Brooch', 'Upgrade', 'Blue', '', '', '', '', false, true, false, '', '', 0, 'PearlBrooch.jpg');
CALL CardDataSet('Perfume Plot White', 'Perfume', 'Plot', 'White', '', '', '', '', true, false, false, 'Confidence', '', 0, 'Perfume.jpg');
CALL CardDataSet('Plant sculpture Plot Green', 'Plant sculpture', 'Plot', 'Green', '', '', '', '', false, true, false, 'Gardening', '', 0, 'Plantsculpture.jpg');
CALL CardDataSet('Plum Blossom Odango Upgrade Blue', 'Plum Blossom Odango', 'Upgrade', 'Blue', '', '', '', '', true, false, false, '', '', 0, 'PlumBlossomOdango.jpg');
CALL CardDataSet('Politician Plot White', 'Politician', 'Plot', 'White', '', '', '', '', false, false, false, 'Organization', '', 0, 'Politician.jpg');
CALL CardDataSet('Poppy Foe Green', 'Poppy', 'Foe', 'Green', '1', '1', '1', '2', true, false, false, 'Regular damage, +target rolls Health 6+ or  is asleep until this foe is defeated, leaves, or target is exorcised of Wood.', '', 0, 'Poppy.jpg');
CALL CardDataSet('Professor Ally Blue', 'Professor', 'Ally', 'Blue', '', '', '', '', true, false, false, 'Math', '', 0, 'Professor.jpg');
CALL CardDataSet('Protect Motive Yellow', 'Protect', 'Motive', 'Yellow', '3', '', '', '4', false, true, false, '', '', 0, 'Protect.jpg');
CALL CardDataSet('Pyrite Privateer Foe Yellow', 'Pyrite Privateer', 'Foe', 'Yellow', '2', '1', '1', '5', false, true, false, 'On attack, discard random card from target player\'s hand.', 'Tempts people with fool\'s gold to do foolish and dishonorable things', 0, 'PyritePrivateer.jpg');
CALL CardDataSet('Red Heart Heart Red', 'Red Heart', 'Heart', 'Red', '', '', '', '', false, true, false, '', 'True humor springs not more from the head than from the heart. It is not contempt; its essence is love. ~ Carlisle', 0, 'RedHeart.jpg');
CALL CardDataSet('Red Hot Rocket Attack Red', 'Red Hot Rocket', 'Attack', 'Red', '1', '1', '', '', false, true, false, '', 'The ancient Chinese invention of gunpowder by Taoist chemists resulted in the development of the rocket.', 0, 'RedHotRocket.jpg');
CALL CardDataSet('Red Lava Lamp Plot Red', 'Red Lava Lamp', 'Plot', 'Red', '', '', '', '', false, false, false, 'Fashion', '', 0, 'RedLavaLamp.jpg');
CALL CardDataSet('Red Star Rising Attack Red', 'Red Star Rising', 'Attack', 'Red', '3', '3', '', '', false, true, false, '', '', 0, 'RedStarRising.jpg');
CALL CardDataSet('Red Steel Fan Upgrade Red', 'Red Steel Fan', 'Upgrade', 'Red', '', '', '', '', false, true, false, '', 'The steel fan can flick deadly force with the grace of a dance.', 0, 'RedSteelFan.jpg');
CALL CardDataSet('Reputation Goal White', 'Reputation', 'Goal', 'White', '4', '', '', '2', true, false, false, 'Friendship +1', '', 0, 'Reputation.jpg');
CALL CardDataSet('Restore Motive Yellow', 'Restore', 'Motive', 'Yellow', '4', '', '', '3', true, false, false, '', '', 0, 'Restore.jpg');
CALL CardDataSet('Right an Injustice Encounter White', 'Right an Injustice', 'Encounter', 'White', '3', '', '6', '', true, false, false, 'Organization +1, Confidence +1', '', 0, 'RightanInjustice.jpg');
CALL CardDataSet('Rival Goal Blue', 'Rival', 'Goal', 'Blue', '4', '', '', '1', true, false, false, 'Diplomacy +1', '', 0, 'Rival.jpg');
CALL CardDataSet('Ruby Lacquer Laser Attack Red', 'Ruby Lacquer Laser', 'Attack', 'Red', '2', '2', '', '', false, true, false, '', '', 0, 'RubyLacquerLaser.jpg');
CALL CardDataSet('Ruby Lotus Bracelets Upgrade Red', 'Ruby Lotus Bracelets', 'Upgrade', 'Red', '', '', '', '', false, true, false, '', '', 0, 'RubyLotusBracelets.jpg');
CALL CardDataSet('Saffron Sandstorm Attack Yellow', 'Saffron Sandstorm', 'Attack', 'Yellow', '1', '', '', '', false, false, false, '', '', 0, 'SaffronSandstorm.jpg');
CALL CardDataSet('Saffron Scarf Upgrade Yellow', 'Saffron Scarf', 'Upgrade', 'Yellow', '', '', '', '', true, false, false, '', '', 0, 'SaffronScarf.jpg');
CALL CardDataSet('Sapphire Splash Attack Blue', 'Sapphire Splash', 'Attack', 'Blue', '1', '1', '', '', false, true, false, '', '', 0, 'SapphireSplash.jpg');
CALL CardDataSet('Save Motive Red', 'Save', 'Motive', 'Red', '4', '', '', '4', true, false, false, '', '', 0, 'Save.jpg');
CALL CardDataSet('Scarlet Macaw Ally Red', 'Scarlet Macaw', 'Ally', 'Red', '', '', '', '', false, false, false, 'Fashion', 'Scarlet Macaws originate in the rain-forests of South America. They can be seen in the wild in the Galapagos Islands.', 0, 'ScarletMacaw.jpg');
CALL CardDataSet('Scarlet Screamer Foe Red', 'Scarlet Screamer', 'Foe', 'Red', '2', '2', '2', '4', true, false, false, 'A haunting, screaming presence. On attack roll of 4 or 5, target must make Bravery roll or may take no action.', '', 0, 'ScarletScreamer.jpg');
CALL CardDataSet('Scarlet Sizzle Attack Red', 'Scarlet Sizzle', 'Attack', 'Red', '1', '', '', '', true, false, false, '', '', 0, 'ScarletSizzle.jpg');
CALL CardDataSet('Scorch Foe Red', 'Scorch', 'Foe', 'Red', '1', '1', '1', '2', false, true, false, 'As an Ally, Scorch adds +1 to attacks on Wood foes.', 'Fire that\'s closest kept burns most of all. ~ William Shakespeare', 0, 'Scorch.jpg');
CALL CardDataSet('Scorpion King Foe White', 'Scorpion King', 'Foe', 'White', '4', '4', '4', '6', true, false, false, 'Can possess allies, causes grief and sadness, depression. Possessed Ally will not aid until defeated/departs.', '', 0, 'ScorpionKing.jpg');
CALL CardDataSet('Serpent Queen Foe Green', 'Serpent Queen', 'Foe', 'Green', '4', '4', '4', '6', true, false, false, 'Attacks elements in preference: yellow, blue green, then clockwise.', '', 0, 'SerpentQueen.jpg');
CALL CardDataSet('Serpentine Spyglass Permanent Yellow', 'Serpentine Spyglass', 'Permanent', 'Yellow', '2', '', '', '', true, false, false, 'See own next Foe', '', 0, 'SerpentineSpyglass.jpg');
CALL CardDataSet('Shout of Thunder Attack Green', 'Shout of Thunder', 'Attack', 'Green', '1', '', '', '', false, false, false, '', '', 0, 'ShoutofThunder.jpg');
CALL CardDataSet('Silver Melon Hammers Attack White', 'Silver Melon Hammers', 'Attack', 'White', '1', '1', '', '', false, true, false, '', '', 0, 'SilverMelonHammers.jpg');
CALL CardDataSet('Silver Zills Instant White', 'Silver Zills', 'Instant', 'White', '', '', '', '', false, false, false, 'Exorcise Wood Foe', '', 0, 'SilverZills.jpg');
CALL CardDataSet('Singer Plot Yellow', 'Singer', 'Plot', 'Yellow', '', '', '', '', false, false, false, 'Singing', '', 0, 'Singer.jpg');
CALL CardDataSet('Singing Stone Plot Yellow', 'Singing Stone', 'Plot', 'Yellow', '', '', '', '', true, false, false, 'Singing', '', 0, 'SingingStone.jpg');
CALL CardDataSet('Sludge Spirit Foe Blue', 'Sludge Spirit', 'Foe', 'Blue', '1', '1', '1', '2', false, false, false, 'A Water Spirit Corrupted by Earth. May be exorcised.', '', 0, 'SludgeSpirit.jpg');
CALL CardDataSet('Smoulder Foe Red', 'Smoulder', 'Foe', 'Red', '1', '1', '1', '2', false, false, false, 'A Fiery Spirit Corrupted by Water. May be exorcised.', '', 0, 'Smoulder.jpg');
CALL CardDataSet('Snow Leopard Plot White', 'Snow Leopard', 'Plot', 'White', '', '', '', '', false, true, false, 'Confidence', '', 0, 'SnowLeopard.jpg');
CALL CardDataSet('Snow Squall Sprite Foe Blue', 'Snow Squall Sprite', 'Foe', 'Blue', '1', '1', '1', '2', false, true, false, 'Convertible', '', 0, 'SnowSquallSprite.jpg');
CALL CardDataSet('Snowflake Obsidian Mirror Permanent Blue', 'Snowflake Obsidian Mirror', 'Permanent', 'Blue', '', '', '', '', false, false, false, 'Target becomes immune to possession by Fire foes', '', 0, 'SnowflakeObsidianMirror.jpg');
CALL CardDataSet('Song of Harmony Instant Yellow', 'Song of Harmony', 'Instant', 'Yellow', '', '', '', '', false, false, false, 'Exorcise Water Foe', '', 0, 'SongofHarmony.jpg');
CALL CardDataSet('Sparkling Spiral Attack White', 'Sparkling Spiral', 'Attack', 'White', '1', '', '', '', false, false, false, '', '', 0, 'SparklingSpiral.jpg');
CALL CardDataSet('Springtime Thorns Attack Green', 'Springtime Thorns', 'Attack', 'Green', '2', '2', '', '', false, true, false, 'Roll, on 5 or 6 target can\'t move next round', '', 0, 'SpringtimeThorns.jpg');
CALL CardDataSet('Stone Shuriken Attack Yellow', 'Stone Shuriken', 'Attack', 'Yellow', '1', '1', '', '', false, true, false, '', 'The four sided shuriken was originally a tool used by carpenters to dig out nails.', 0, 'StoneShuriken.jpg');
CALL CardDataSet('Stoneskin Oni Foe Yellow', 'Stoneskin Oni', 'Foe', 'Yellow', '2', '2', '2', '4', true, false, false, 'Strong and tough', '', 0, 'StoneskinOni.jpg');
CALL CardDataSet('Substitute Coach Encounter Red', 'Substitute Coach', 'Encounter', 'Red', '3', '', '6', '', false, true, false, 'Be a substitute coach for a team. Leadership +1.', '', 0, 'SubstituteCoach.jpg');
CALL CardDataSet('Sweet Lemon Surprise Attack Yellow', 'Sweet Lemon Surprise', 'Attack', 'Yellow', '1', '', '', '', true, false, false, '', 'When life sends you lemons, make lemon meringue pie!', 0, 'SweetLemonSurprise.jpg');
CALL CardDataSet('Talent Contest Encounter Red', 'Talent Contest', 'Encounter', 'Red', '1', '', '6', '', true, false, false, 'Acting OR Singing OR Humor', 'Hide not your talents, they for use were made. What\'s a sun-dial in the shade? ~ Benjamin Franklin', 0, 'TalentContest.jpg');
CALL CardDataSet('Tawny Troll Foe Yellow', 'Tawny Troll', 'Foe', 'Yellow', '1', '1', '1', '2', false, true, false, 'Can be converted to ally', '', 0, 'TawnyTroll.jpg');
CALL CardDataSet('Tea Garden Plot Green', 'Tea Garden', 'Plot', 'Green', '', '', '', '', true, false, false, 'Gardening', '', 0, 'TeaGarden.jpg');
CALL CardDataSet('Teacher Plot Green', 'Teacher', 'Plot', 'Green', '', '', '', '', false, false, false, 'Art', '', 0, 'Teacher.jpg');
CALL CardDataSet('Tempering Forge Flame Instant Red', 'Tempering Forge Flame', 'Instant', 'Red', '', '', '', '', false, false, false, 'Exorcise Metal Foe', '', 0, 'TemperingForgeFlame.jpg');
CALL CardDataSet('Terra Cotta Talisman Upgrade Yellow', 'Terra Cotta Talisman', 'Upgrade', 'Yellow', '', '', '', '', false, true, false, '', '', 0, 'TerraCottaTalisman.jpg');
CALL CardDataSet('Theatre stage Plot Red', 'Theatre stage', 'Plot', 'Red', '', '', '', '', true, false, false, 'Acting', 'All the world\'s a stage, and we are merely players... ~ Shakespeare', 0, 'Theatrestage.jpg');
CALL CardDataSet('Tiger\'s Tambourine Upgrade White', 'Tiger\'s Tambourine', 'Upgrade', 'White', '', '', '', '', true, false, false, '', '', 0, 'Tiger\'sTambourine.jpg');
CALL CardDataSet('Triple Torch Trick Attack Red', 'Triple Torch Trick', 'Attack', 'Red', '3', '3', '', '', true, false, false, '', '', 0, 'TripleTorchTrick.jpg');
CALL CardDataSet('Turquoise Tsunami Attack Blue', 'Turquoise Tsunami', 'Attack', 'Blue', '2', '2', '', '', false, true, false, '', '', 0, 'TurquoiseTsunami.jpg');
CALL CardDataSet('Turquoise Tortoise Upgrade Blue', 'Turquoise Tortoise', 'Upgrade', 'Blue', '', '', '', '', true, false, false, '', '', 0, 'TurquoiseTortoise.jpg');
CALL CardDataSet('Two Friends Fighting Encounter Yellow', 'Two Friends Fighting', 'Encounter', 'Yellow', '3', '', '6', '', true, false, false, 'Two allies will not aid until resolved. Friendship +1', '', 0, 'TwoFriendsFighting.jpg');
CALL CardDataSet('Unakite Foe Yellow', 'Unakite', 'Foe', 'Yellow', '4', '3', '4', '6', true, false, false, 'On Attack, reopens a resolved Encounter.', 'Unakite is said to enhance vision of the etheral plane.', 0, 'Unakite.jpg');
CALL CardDataSet('Underwater City Stronghold Blue', 'Underwater City', 'Stronghold', 'Blue', '5', '', '4', '', false, true, false, '', '', 0, 'UnderwaterCity.jpg');
CALL CardDataSet('Verdant Labyrinth Instant Green', 'Verdant Labyrinth', 'Instant', 'Green', '', '', '', '', false, true, false, 'Target loses a turn', '', 0, 'VerdantLabyrinth.jpg');
CALL CardDataSet('Vermillion Votive Upgrade Red', 'Vermillion Votive', 'Upgrade', 'Red', '', '', '', '', true, false, false, '', 'If you are the first snow, I am he who lights the hearth of dawn. ~ Octavio Paz', 0, 'VermillionVotive.jpg');
CALL CardDataSet('Vinia Foe Green', 'Vinia', 'Foe', 'Green', '1', '1', '1', '2', false, false, false, 'Distractingly itchy - targets attack at -1 until this foe is defeated or leaves.', '', 0, 'Vinia.jpg');
CALL CardDataSet('Viridian Veil Upgrade Green', 'Viridian Veil', 'Upgrade', 'Green', '', '', '', '', true, false, false, '', '', 0, 'ViridianVeil.jpg');
CALL CardDataSet('Water Accident Encounter Blue', 'Water Accident', 'Encounter', 'Blue', '1', '', '4', '', true, false, false, 'Swimming +1', '', 0, 'WaterAccident.jpg');
CALL CardDataSet('Wealth Goal White', 'Wealth', 'Goal', 'White', '2', '', '', '2', false, true, false, 'Money+1', '', 0, 'Wealth.jpg');
CALL CardDataSet('Whisper of Winter Instant Blue', 'Whisper of Winter', 'Instant', 'Blue', '', '', '', '', false, false, false, 'Exorcise Fire Foe', '', 0, 'WhisperofWinter.jpg');
CALL CardDataSet('White Cat Ally White', 'White Cat', 'Ally', 'White', '', '', '', '', false, true, false, 'Intuition', '', 0, 'WhiteCat.jpg');
CALL CardDataSet('White Gold Tiara Upgrade White', 'White Gold Tiara', 'Upgrade', 'White', '', '', '', '', true, false, false, '', '', 0, 'WhiteGoldTiara.jpg');
CALL CardDataSet('White Heart Heart White', 'White Heart', 'Heart', 'White', '', '', '', '', false, true, false, '', '', 0, 'WhiteHeart.jpg');
CALL CardDataSet('Wildwood Tangle Instant Green', 'Wildwood Tangle', 'Instant', 'Green', '2', '-1', '', '', true, false, false, 'Target attacks at -1. May be played as target is attacking.', '', 0, 'WildwoodTangle.jpg');
CALL CardDataSet('Will-o-wisp Foe White', 'Will-o-wisp', 'Foe', 'White', '1', '1', '1', '2', false, true, false, 'Leads an ally away for 1 turn, Convertible', '', 0, 'Will-o-wisp.jpg');
CALL CardDataSet('Wilting Garden Encounter Green', 'Wilting Garden', 'Encounter', 'Green', '2', '', '5', '', false, true, false, 'Gardening +1', '', 0, 'WiltingGarden.jpg');
CALL CardDataSet('Withering Touch Foe White', 'Withering Touch', 'Foe', 'White', '2', '2', '2', '4', true, false, false, 'Weakens, as with age (target attacks -1 until healed)', '', 0, 'WitheringTouch.jpg');
CALL CardDataSet('Yellow Heart Heart Yellow', 'Yellow Heart', 'Heart', 'Yellow', '', '', '', '', false, true, false, '', '', 0, 'YellowHeart.jpg');
CALL CardDataSet('Yellow Jade Bangle Upgrade Yellow', 'Yellow Jade Bangle', 'Upgrade', 'Yellow', '', '', '', '', false, true, false, '', 'Jade is an ancient symbol of love and virtue.', 0, 'YellowJadeBangle.jpg');
CALL CardDataSet('Yellow Lizard Foe Yellow', 'Yellow Lizard', 'Foe', 'Yellow', '1', '1', '1', '2', false, false, false, 'poisonous lizard', '', 0, 'YellowLizard.jpg');
CALL CardDataSet('Yeti Foe Blue', 'Yeti', 'Foe', 'Blue', '2', '2', '2', '4', false, true, false, 'The temperament of a polar bear - with opposable thumbs.', '', 0, 'Yeti.jpg');
CALL CardDataSet('Yew Foe Green', 'Yew', 'Foe', 'Green', '3', '3', '3', '4', false, true, false, '', '', 0, 'Yew.jpg');
CALL CardDataSet('Zone of Diamonds Upgrade White', 'Zone of Diamonds', 'Upgrade', 'White', '', '', '', '', true, false, false, '', 'Marie Antoinette wore this fantastic belt of diamonds that circled her waist and dropped to the floor.', 0, 'ZoneofDiamonds.jpg');
CALL CardDataSet('Beacon of the North Star Permanent Yellow', 'Beacon of the North Star', 'Permanent', 'Yellow', '3', '', '', '', false, false, true, 'Target is immune to possession or mood-based attacks', 'Navigate by this constant star, and you will never lose your way.', 0, 'BeaconoftheNorthStar.jpg');
CALL CardDataSet('Belladonna Foe Green', 'Belladonna', 'Foe', 'Green', '5', '5', '5', '11', false, false, true, '', 'The Deadly Nightshade family also includes tomatoes, potatoes, peppers, and eggplant, though Belladonna is far more toxic than these.', 0, 'Belladonna.jpg');
CALL CardDataSet('Computer Plot Blue', 'Computer', 'Plot', 'Blue', '', '', '', '', false, false, true, 'Science, Automatic Clue', '', 0, 'Computer.jpg');
CALL CardDataSet('Dancing Dragon Instant Green', 'Dancing Dragon', 'Instant', 'Green', '2', '', '', '', false, false, true, 'Restore 1 player to full strength', '', 0, 'DancingDragon.jpg');
CALL CardDataSet('Dragonette Ally Green', 'Dragonette', 'Ally', 'Green', '', '', '', '', false, false, true, 'Creativity', '', 0, 'Dragonette.jpg');
CALL CardDataSet('First Spring\'s Growth Instant Green', 'First Spring\'s Growth', 'Instant', 'Green', '2', '', '', '', false, false, true, 'Any card worth 2x for 1 turn', '', 0, 'FirstSpring\'sGrowth.jpg');
CALL CardDataSet('Galena Foe White', 'Galena', 'Foe', 'White', '5', '5', '5', '11', false, false, true, 'Possesses an Ally as a level 2 Foe, 2 Hearts will exorcise.', 'This ruler of the underworld  is very pale, with white hair and  armor made of lead.', 0, 'Galena.jpg');
CALL CardDataSet('Grandmother Ally Blue', 'Grandmother', 'Ally', 'Blue', '', '', '', '', false, false, true, 'Diplomacy, Clue Action', '', 0, 'Grandmother.jpg');
CALL CardDataSet('Jeweler Ally White', 'Jeweler', 'Ally', 'White', '', '', '', '', false, false, true, 'Crafts AND Creativity AND Fashion', '', 0, 'Jeweler.jpg');
CALL CardDataSet('Kronos Foe Yellow', 'Kronos', 'Foe', 'Yellow', '5', '5', '5', '11', false, false, true, '', '', 0, 'Kronos.jpg');
CALL CardDataSet('Loyalty of the Burning Heart Instant Red', 'Loyalty of the Burning Heart', 'Instant', 'Red', '2', '', '', '', false, false, true, 'Worth thee hearts - discard after use', '', 0, 'LoyaltyoftheBurningHeart.jpg');
CALL CardDataSet('Meandering River of Time Instant Blue', 'Meandering River of Time', 'Instant', 'Blue', '2', '', '', '', false, false, true, 'Take an extra turn anytime, play resumes as normal after this interruption', '', 0, 'MeanderingRiverofTime.jpg');
CALL CardDataSet('Miko Ally Red', 'Miko', 'Ally', 'Red', '', '', '', '', false, false, true, 'Can exorcise 1target/turn.', '', 0, 'Miko.jpg');
CALL CardDataSet('Pet monkey Ally Yellow', 'Pet monkey', 'Ally', 'Yellow', '', '', '', '', false, false, true, 'Friendship, may use Player\'s action to reveal a Clue', '', 0, 'Petmonkey.jpg');
CALL CardDataSet('Rejuvenating Laughter Attack Red', 'Rejuvenating Laughter', 'Attack', 'Red', '3', '3', '', '', false, false, true, 'All allies + 3 healing in addition to damage to Foe. Save this as a Humor Plot card.', 'Laughter is the tonic, the relief, the surcease for pain. ~ Charlie Chaplin', 0, 'RejuvenatingLaughter.jpg');
CALL CardDataSet('Rogue Star Regina Foe Red', 'Rogue Star Regina', 'Foe', 'Red', '5', '5', '5', '15', false, false, true, '', '', 0, 'RogueStarRegina.jpg');
CALL CardDataSet('Sacred Vessel Instant White', 'Sacred Vessel', 'Instant', 'White', '2', '', '', '', false, false, true, 'Heal any Player 3 Health', '', 0, 'SacredVessel.jpg');
CALL CardDataSet('Will of Stone Instant Yellow', 'Will of Stone', 'Instant', 'Yellow', '2', '', '', '', false, false, true, 'Negate 1 card for 1 turn', '', 0, 'WillofStone.jpg');
CALL CardDataSet('Winter Queen Foe Blue', 'Winter Queen', 'Foe', 'Blue', '5', '5', '5', '11', false, false, true, '', 'I think I know enough of hate to say that Ice is also great, and would suffice. ~ Robert Frost', 0, 'WinterQueen.jpg');
CALL CardDataSet('Zen Monk Ally White', 'Zen Monk', 'Ally', 'White', '', '', '', '', false, false, true, 'Intuition, Clue Action', 'Do not seek to follow in the footsteps of the men of old; seek what they sought. ~ Basho', 0, 'ZenMonk.jpg');
CALL PlayerCardsSet('admin', 'Abandoned Castle Stronghold Yellow', 1);
CALL PlayerCardsSet('admin', 'Abandoned Idol Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Adobe Avalanche Attack Yellow', 1);
CALL PlayerCardsSet('admin', 'Agate Armor Permanent Yellow', 1);
CALL PlayerCardsSet('admin', 'Agate Comb Upgrade Yellow', 1);
CALL PlayerCardsSet('admin', 'Amazon Jungle Stronghold Green', 1);
CALL PlayerCardsSet('admin', 'Amusement Park Plot Red', 1);
CALL PlayerCardsSet('admin', 'Ancestral Home Goal Yellow', 1);
CALL PlayerCardsSet('admin', 'Ancient Enemy Goal Red', 1);
CALL PlayerCardsSet('admin', 'Ancient Shrine Stronghold White', 1);
CALL PlayerCardsSet('admin', 'Ankle Bells Upgrade White', 1);
CALL PlayerCardsSet('admin', 'Apple Amber Amulet Upgrade Green', 1);
CALL PlayerCardsSet('admin', 'Art Contest Encounter Green', 1);
CALL PlayerCardsSet('admin', 'Avoid Motive Blue', 1);
CALL PlayerCardsSet('admin', 'Baby Brother Ally Green', 1);
CALL PlayerCardsSet('admin', 'Babysitting Encounter Yellow', 1);
CALL PlayerCardsSet('admin', 'Banshee Foe White', 1);
CALL PlayerCardsSet('admin', 'Beach Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Blazing Arrow Attack Red', 1);
CALL PlayerCardsSet('admin', 'Blue Heart Heart Blue', 1);
CALL PlayerCardsSet('admin', 'Blue Ice Comet Attack Blue', 1);
CALL PlayerCardsSet('admin', 'Bookstore Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Brilliant Rose Attack Red', 1);
CALL PlayerCardsSet('admin', 'Burning Rider Foe Red', 1);
CALL PlayerCardsSet('admin', 'Businesswoman Ally White', 1);
CALL PlayerCardsSet('admin', 'Cake Shop Plot Yellow', 1);
CALL PlayerCardsSet('admin', 'Canary Chorus Permanent Yellow', 1);
CALL PlayerCardsSet('admin', 'Capture Motive White', 1);
CALL PlayerCardsSet('admin', 'Cardinal Plot Red', 1);
CALL PlayerCardsSet('admin', 'Carmine Conflagration Attack Red', 1);
CALL PlayerCardsSet('admin', 'Carnelian Crossbow Attack Red', 1);
CALL PlayerCardsSet('admin', 'Carpenter Plot Green', 1);
CALL PlayerCardsSet('admin', 'Cave Plot Yellow', 1);
CALL PlayerCardsSet('admin', 'Celestial Retribution Attack White', 1);
CALL PlayerCardsSet('admin', 'Center of the Earth Stronghold Yellow', 1);
CALL PlayerCardsSet('admin', 'Cerulean Spray Attack Blue', 1);
CALL PlayerCardsSet('admin', 'Chartreuse Chinook Instant Green', 1);
CALL PlayerCardsSet('admin', 'Chef Plot Yellow', 1);
CALL PlayerCardsSet('admin', 'Cinnibar Pendant Upgrade Red', 1);
CALL PlayerCardsSet('admin', 'Clack Foe White', 1);
CALL PlayerCardsSet('admin', 'Classmate Ally Yellow', 1);
CALL PlayerCardsSet('admin', 'Click Foe White', 1);
CALL PlayerCardsSet('admin', 'Clown Plot Red', 1);
CALL PlayerCardsSet('admin', 'Cobalt Centipede Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Conquer Motive White', 1);
CALL PlayerCardsSet('admin', 'Cooking Contest Encounter Yellow', 1);
CALL PlayerCardsSet('admin', 'Cousin Ally Yellow', 1);
CALL PlayerCardsSet('admin', 'Crab Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Cram School Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Crystal Caves Permanent Yellow', 1);
CALL PlayerCardsSet('admin', 'Crystal Unicorn Plot Yellow', 1);
CALL PlayerCardsSet('admin', 'Damaged Dress Encounter Red', 1);
CALL PlayerCardsSet('admin', 'Dark Cloud Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Deer Plot Green', 1);
CALL PlayerCardsSet('admin', 'Destroy Motive Red', 1);
CALL PlayerCardsSet('admin', 'Detective Ally White', 1);
CALL PlayerCardsSet('admin', 'Doctor Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Electrum Net Permanent White', 1);
CALL PlayerCardsSet('admin', 'Emerald Nebula Attack Green', 1);
CALL PlayerCardsSet('admin', 'Escape Motive Green', 1);
CALL PlayerCardsSet('admin', 'Evergreen Enchantment Instant Green', 1);
CALL PlayerCardsSet('admin', 'Exam Encounter Blue', 1);
CALL PlayerCardsSet('admin', 'Face a Bully Encounter Red', 1);
CALL PlayerCardsSet('admin', 'Falling Fieldstone Wall Permanent Yellow', 1);
CALL PlayerCardsSet('admin', 'Family Member Goal Yellow', 1);
CALL PlayerCardsSet('admin', 'Fashion Show Encounter Red', 1);
CALL PlayerCardsSet('admin', 'Father Ally White', 1);
CALL PlayerCardsSet('admin', 'Feisty Fiesta Attack Red', 1);
CALL PlayerCardsSet('admin', 'Fencing Match Encounter White', 1);
CALL PlayerCardsSet('admin', 'Find Motive Blue', 1);
CALL PlayerCardsSet('admin', 'Fire Toad Foe Red', 1);
CALL PlayerCardsSet('admin', 'Fire Triangle Earrings Upgrade Red', 1);
CALL PlayerCardsSet('admin', 'Fisherman Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Florist Plot White', 1);
CALL PlayerCardsSet('admin', 'Flower Power Beads Upgrade Green', 1);
CALL PlayerCardsSet('admin', 'Flower Show Encounter Green', 1);
CALL PlayerCardsSet('admin', 'Foot Race Encounter Green', 1);
CALL PlayerCardsSet('admin', 'Forest Flutesong Instant Green', 1);
CALL PlayerCardsSet('admin', 'Fountain Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Foxglove Foe Green', 1);
CALL PlayerCardsSet('admin', 'Fragrant Chrysanthemum Attack White', 1);
CALL PlayerCardsSet('admin', 'Free Motive Green', 1);
CALL PlayerCardsSet('admin', 'Gaia\'s Gift Permanent Green', 1);
CALL PlayerCardsSet('admin', 'Gardener Ally Green', 1);
CALL PlayerCardsSet('admin', 'Geode Jewel Upgrade Yellow', 1);
CALL PlayerCardsSet('admin', 'Giant Oyster Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Glittering Ice Chimes Attack Blue', 1);
CALL PlayerCardsSet('admin', 'Green Heart Heart Green', 1);
CALL PlayerCardsSet('admin', 'Greenhouse Plot Green', 1);
CALL PlayerCardsSet('admin', 'Hand Flower Upgrade White', 1);
CALL PlayerCardsSet('admin', 'Harvest Moon Halo Attack Yellow', 1);
CALL PlayerCardsSet('admin', 'Hateful Sparks Foe Red', 1);
CALL PlayerCardsSet('admin', 'Haunted Forest Stronghold Green', 1);
CALL PlayerCardsSet('admin', 'Heart of a Volcano Stronghold Red', 1);
CALL PlayerCardsSet('admin', 'Heaven\'s Lament Attack White', 1);
CALL PlayerCardsSet('admin', 'Hemlock Foe Green', 1);
CALL PlayerCardsSet('admin', 'Homeworld Goal Green', 1);
CALL PlayerCardsSet('admin', 'HotBot Foe White', 1);
CALL PlayerCardsSet('admin', 'Identify Artifact Encounter Blue', 1);
CALL PlayerCardsSet('admin', 'Incredible Sale! Plot White', 1);
CALL PlayerCardsSet('admin', 'Indigo Infinity Attack Blue', 1);
CALL PlayerCardsSet('admin', 'Injured Friend Encounter Yellow', 1);
CALL PlayerCardsSet('admin', 'Ivy Metallica Foe Green', 1);
CALL PlayerCardsSet('admin', 'Jade Peony Barrettes Upgrade Green', 1);
CALL PlayerCardsSet('admin', 'Jasmine Javelin Attack Green', 1);
CALL PlayerCardsSet('admin', 'Jasper Statuette Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Jeweled Tortoise Ally Blue', 1);
CALL PlayerCardsSet('admin', 'Jewelry Store Plot White', 1);
CALL PlayerCardsSet('admin', 'Jungle Storm Attack Green', 1);
CALL PlayerCardsSet('admin', 'Keep a Secret Encounter Blue', 1);
CALL PlayerCardsSet('admin', 'Ki-Rin Goal Green', 1);
CALL PlayerCardsSet('admin', 'Koi Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Lake Pollution Encounter Blue', 1);
CALL PlayerCardsSet('admin', 'Lapis Lazuli Locket Upgrade Blue', 1);
CALL PlayerCardsSet('admin', 'Leafy Lenses Upgrade Green', 1);
CALL PlayerCardsSet('admin', 'Librarian Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Lifeguard Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Lime Lariat Attack Green', 1);
CALL PlayerCardsSet('admin', 'Little Sister Ally Red', 1);
CALL PlayerCardsSet('admin', 'Lost Island Stronghold Blue', 1);
CALL PlayerCardsSet('admin', 'Lost Pet Encounter White', 1);
CALL PlayerCardsSet('admin', 'Magma Burst Attack Red', 1);
CALL PlayerCardsSet('admin', 'Magnetic Meteor Attack White', 1);
CALL PlayerCardsSet('admin', 'Mahalat Foe Red', 1);
CALL PlayerCardsSet('admin', 'Make a Gift Encounter Yellow', 1);
CALL PlayerCardsSet('admin', 'Martial Artist Ally White', 1);
CALL PlayerCardsSet('admin', 'Money Worries Encounter White', 1);
CALL PlayerCardsSet('admin', 'Mother Ally White', 1);
CALL PlayerCardsSet('admin', 'Movie star Plot Red', 1);
CALL PlayerCardsSet('admin', 'Mystical Amulet Goal Blue', 1);
CALL PlayerCardsSet('admin', 'Naamah Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Nature Hike Encounter Green', 1);
CALL PlayerCardsSet('admin', 'Ochre Aftershock Attack Yellow', 1);
CALL PlayerCardsSet('admin', 'Opal Ear Drops Upgrade Blue', 1);
CALL PlayerCardsSet('admin', 'Orbiting Space Station Stronghold White', 1);
CALL PlayerCardsSet('admin', 'Organize School Festival Encounter White', 1);
CALL PlayerCardsSet('admin', 'Palace of the Sun Stronghold Red', 1);
CALL PlayerCardsSet('admin', 'Pearl Brooch Upgrade Blue', 1);
CALL PlayerCardsSet('admin', 'Perfume Plot White', 1);
CALL PlayerCardsSet('admin', 'Plant sculpture Plot Green', 1);
CALL PlayerCardsSet('admin', 'Plum Blossom Odango Upgrade Blue', 1);
CALL PlayerCardsSet('admin', 'Politician Plot White', 1);
CALL PlayerCardsSet('admin', 'Poppy Foe Green', 1);
CALL PlayerCardsSet('admin', 'Professor Ally Blue', 1);
CALL PlayerCardsSet('admin', 'Protect Motive Yellow', 1);
CALL PlayerCardsSet('admin', 'Pyrite Privateer Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Red Heart Heart Red', 1);
CALL PlayerCardsSet('admin', 'Red Hot Rocket Attack Red', 1);
CALL PlayerCardsSet('admin', 'Red Lava Lamp Plot Red', 1);
CALL PlayerCardsSet('admin', 'Red Star Rising Attack Red', 1);
CALL PlayerCardsSet('admin', 'Red Steel Fan Upgrade Red', 1);
CALL PlayerCardsSet('admin', 'Reputation Goal White', 1);
CALL PlayerCardsSet('admin', 'Restore Motive Yellow', 1);
CALL PlayerCardsSet('admin', 'Right an Injustice Encounter White', 1);
CALL PlayerCardsSet('admin', 'Rival Goal Blue', 1);
CALL PlayerCardsSet('admin', 'Ruby Lacquer Laser Attack Red', 1);
CALL PlayerCardsSet('admin', 'Ruby Lotus Bracelets Upgrade Red', 1);
CALL PlayerCardsSet('admin', 'Saffron Sandstorm Attack Yellow', 1);
CALL PlayerCardsSet('admin', 'Saffron Scarf Upgrade Yellow', 1);
CALL PlayerCardsSet('admin', 'Sapphire Splash Attack Blue', 1);
CALL PlayerCardsSet('admin', 'Save Motive Red', 1);
CALL PlayerCardsSet('admin', 'Scarlet Macaw Ally Red', 1);
CALL PlayerCardsSet('admin', 'Scarlet Screamer Foe Red', 1);
CALL PlayerCardsSet('admin', 'Scarlet Sizzle Attack Red', 1);
CALL PlayerCardsSet('admin', 'Scorch Foe Red', 1);
CALL PlayerCardsSet('admin', 'Scorpion King Foe White', 1);
CALL PlayerCardsSet('admin', 'Serpent Queen Foe Green', 1);
CALL PlayerCardsSet('admin', 'Serpentine Spyglass Permanent Yellow', 1);
CALL PlayerCardsSet('admin', 'Shout of Thunder Attack Green', 1);
CALL PlayerCardsSet('admin', 'Silver Melon Hammers Attack White', 1);
CALL PlayerCardsSet('admin', 'Silver Zills Instant White', 1);
CALL PlayerCardsSet('admin', 'Singer Plot Yellow', 1);
CALL PlayerCardsSet('admin', 'Singing Stone Plot Yellow', 1);
CALL PlayerCardsSet('admin', 'Sludge Spirit Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Smoulder Foe Red', 1);
CALL PlayerCardsSet('admin', 'Snow Leopard Plot White', 1);
CALL PlayerCardsSet('admin', 'Snow Squall Sprite Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Snowflake Obsidian Mirror Permanent Blue', 1);
CALL PlayerCardsSet('admin', 'Song of Harmony Instant Yellow', 1);
CALL PlayerCardsSet('admin', 'Sparkling Spiral Attack White', 1);
CALL PlayerCardsSet('admin', 'Springtime Thorns Attack Green', 1);
CALL PlayerCardsSet('admin', 'Stone Shuriken Attack Yellow', 1);
CALL PlayerCardsSet('admin', 'Stoneskin Oni Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Substitute Coach Encounter Red', 1);
CALL PlayerCardsSet('admin', 'Sweet Lemon Surprise Attack Yellow', 1);
CALL PlayerCardsSet('admin', 'Talent Contest Encounter Red', 1);
CALL PlayerCardsSet('admin', 'Tawny Troll Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Tea Garden Plot Green', 1);
CALL PlayerCardsSet('admin', 'Teacher Plot Green', 1);
CALL PlayerCardsSet('admin', 'Tempering Forge Flame Instant Red', 1);
CALL PlayerCardsSet('admin', 'Terra Cotta Talisman Upgrade Yellow', 1);
CALL PlayerCardsSet('admin', 'Theatre stage Plot Red', 1);
CALL PlayerCardsSet('admin', 'Tiger\'s Tambourine Upgrade White', 1);
CALL PlayerCardsSet('admin', 'Triple Torch Trick Attack Red', 1);
CALL PlayerCardsSet('admin', 'Turquoise Tsunami Attack Blue', 1);
CALL PlayerCardsSet('admin', 'Turquoise Tortoise Upgrade Blue', 1);
CALL PlayerCardsSet('admin', 'Two Friends Fighting Encounter Yellow', 1);
CALL PlayerCardsSet('admin', 'Unakite Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Underwater City Stronghold Blue', 1);
CALL PlayerCardsSet('admin', 'Verdant Labyrinth Instant Green', 1);
CALL PlayerCardsSet('admin', 'Vermillion Votive Upgrade Red', 1);
CALL PlayerCardsSet('admin', 'Vinia Foe Green', 1);
CALL PlayerCardsSet('admin', 'Viridian Veil Upgrade Green', 1);
CALL PlayerCardsSet('admin', 'Water Accident Encounter Blue', 1);
CALL PlayerCardsSet('admin', 'Wealth Goal White', 1);
CALL PlayerCardsSet('admin', 'Whisper of Winter Instant Blue', 1);
CALL PlayerCardsSet('admin', 'White Cat Ally White', 1);
CALL PlayerCardsSet('admin', 'White Gold Tiara Upgrade White', 1);
CALL PlayerCardsSet('admin', 'White Heart Heart White', 1);
CALL PlayerCardsSet('admin', 'Wildwood Tangle Instant Green', 1);
CALL PlayerCardsSet('admin', 'Will-o-wisp Foe White', 1);
CALL PlayerCardsSet('admin', 'Wilting Garden Encounter Green', 1);
CALL PlayerCardsSet('admin', 'Withering Touch Foe White', 1);
CALL PlayerCardsSet('admin', 'Yellow Heart Heart Yellow', 1);
CALL PlayerCardsSet('admin', 'Yellow Jade Bangle Upgrade Yellow', 1);
CALL PlayerCardsSet('admin', 'Yellow Lizard Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Yeti Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Yew Foe Green', 1);
CALL PlayerCardsSet('admin', 'Zone of Diamonds Upgrade White', 1);
CALL PlayerCardsSet('admin', 'Beacon of the North Star Permanent Yellow', 1);
CALL PlayerCardsSet('admin', 'Belladonna Foe Green', 1);
CALL PlayerCardsSet('admin', 'Computer Plot Blue', 1);
CALL PlayerCardsSet('admin', 'Dancing Dragon Instant Green', 1);
CALL PlayerCardsSet('admin', 'Dragonette Ally Green', 1);
CALL PlayerCardsSet('admin', 'First Spring\'s Growth Instant Green', 1);
CALL PlayerCardsSet('admin', 'Galena Foe White', 1);
CALL PlayerCardsSet('admin', 'Grandmother Ally Blue', 1);
CALL PlayerCardsSet('admin', 'Jeweler Ally White', 1);
CALL PlayerCardsSet('admin', 'Kronos Foe Yellow', 1);
CALL PlayerCardsSet('admin', 'Loyalty of the Burning Heart Instant Red', 1);
CALL PlayerCardsSet('admin', 'Meandering River of Time Instant Blue', 1);
CALL PlayerCardsSet('admin', 'Miko Ally Red', 1);
CALL PlayerCardsSet('admin', 'Pet monkey Ally Yellow', 1);
CALL PlayerCardsSet('admin', 'Rejuvenating Laughter Attack Red', 1);
CALL PlayerCardsSet('admin', 'Rogue Star Regina Foe Red', 1);
CALL PlayerCardsSet('admin', 'Sacred Vessel Instant White', 1);
CALL PlayerCardsSet('admin', 'Will of Stone Instant Yellow', 1);
CALL PlayerCardsSet('admin', 'Winter Queen Foe Blue', 1);
CALL PlayerCardsSet('admin', 'Zen Monk Ally White', 1);
