package CorbaHelloApp;

/**
* CorbaHelloApp/CorbaHelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaHello.idl
*/

public final class CorbaHelloHolder implements org.omg.CORBA.portable.Streamable
{
  public CorbaHelloApp.CorbaHello value = null;

  public CorbaHelloHolder ()
  {
  }

  public CorbaHelloHolder (CorbaHelloApp.CorbaHello initialValue)
  {
      value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
      value = CorbaHelloApp.CorbaHelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
      CorbaHelloApp.CorbaHelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
      return CorbaHelloApp.CorbaHelloHelper.type ();
  }
}
