package CorbaHelloApp;

/**
* CorbaHelloApp/CorbaHello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaHello.idl
*/

public interface CorbaHello extends CorbaHelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaHello
