package CorbaHelloApp;

/**
* CorbaHelloApp/CorbaHelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaHello.idl
*/

public interface CorbaHelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface CorbaHelloOperations
