package CorbaHelloApp;

/**
* CorbaHelloApp/CorbaHelloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaHello.idl
*/

abstract public class CorbaHelloHelper
{
    private static String  _id = "IDL:CorbaHelloApp/CorbaHello:1.0";

    public static void insert (org.omg.CORBA.Any a, CorbaHelloApp.CorbaHello that)
    {
        org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
        a.type (type ());
        write (out, that);
        a.read_value (out.create_input_stream (), type ());
    }

    public static CorbaHelloApp.CorbaHello extract (org.omg.CORBA.Any a)
    {
        return read (a.create_input_stream ());
    }

    private static org.omg.CORBA.TypeCode __typeCode = null;
    synchronized public static org.omg.CORBA.TypeCode type ()
    {
        if (__typeCode == null)
        {
          __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CorbaHelloApp.CorbaHelloHelper.id (), "CorbaHello");
        }
        return __typeCode;
    }

    public static String id ()
    {
        return _id;
    }

    public static CorbaHelloApp.CorbaHello read (org.omg.CORBA.portable.InputStream istream)
    {
        return narrow (istream.read_Object (_CorbaHelloStub.class));
    }

    public static void write (org.omg.CORBA.portable.OutputStream ostream, CorbaHelloApp.CorbaHello value)
    {
        ostream.write_Object ((org.omg.CORBA.Object) value);
    }

    public static CorbaHelloApp.CorbaHello narrow (org.omg.CORBA.Object obj)
    {
        if (obj == null)
          return null;
        else if (obj instanceof CorbaHelloApp.CorbaHello)
          return (CorbaHelloApp.CorbaHello)obj;
        else if (!obj._is_a (id ()))
          throw new org.omg.CORBA.BAD_PARAM ();
        else
        {
            org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
            CorbaHelloApp._CorbaHelloStub stub = new CorbaHelloApp._CorbaHelloStub ();
            stub._set_delegate(delegate);
            return stub;
        }
    }

    public static CorbaHelloApp.CorbaHello unchecked_narrow (org.omg.CORBA.Object obj)
    {
      if (obj == null)
        return null;
      else if (obj instanceof CorbaHelloApp.CorbaHello)
        return (CorbaHelloApp.CorbaHello)obj;
      else
      {
          org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
          CorbaHelloApp._CorbaHelloStub stub = new CorbaHelloApp._CorbaHelloStub ();
          stub._set_delegate(delegate);
          return stub;
      }
    }
}
